/**
 * This program is free software, you can redistribute it and/or modify.
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING
 * BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/*!
 * \file transposev_tiling_key.h
 * \brief transposev tiling key declare
 */
#ifndef __TRANSPOSEV_TILING_KEY_H__
#define __TRANSPOSEV_TILING_KEY_H__

#include "ascendc/host_api/tiling/template_argument.h"

#define ELEMENTWISE_TPL_SCH_MODE_0 0
#define ELEMENTWISE_TPL_SCH_MODE_1 1
#define ELEMENTWISE_TPL_SCH_MODE_2 2
#define ELEMENTWISE_TPL_SCH_MODE_3 3
#define ELEMENTWISE_TPL_SCH_MODE_4 4
#define ELEMENTWISE_TPL_SCH_MODE_5 5
#define ELEMENTWISE_TPL_SCH_MODE_6 6
#define ELEMENTWISE_TPL_SCH_MODE_7 7
#define ELEMENTWISE_TPL_SCH_MODE_8 8
#define ELEMENTWISE_TPL_SCH_MODE_9 9
#define ELEMENTWISE_TPL_SCH_MODE_10 10
#define ELEMENTWISE_TPL_SCH_MODE_11 11
#define ELEMENTWISE_TPL_SCH_MODE_12 12
#define ELEMENTWISE_TPL_SCH_MODE_13 13
#define ELEMENTWISE_TPL_SCH_MODE_14 14
#define ELEMENTWISE_TPL_SCH_MODE_15 15
#define ELEMENTWISE_TPL_SCH_MODE_16 16
#define ELEMENTWISE_TPL_SCH_MODE_17 17
#define ELEMENTWISE_TPL_SCH_MODE_18 18
#define ELEMENTWISE_TPL_SCH_MODE_19 19
#define ELEMENTWISE_TPL_SCH_MODE_20 20
#define ELEMENTWISE_TPL_SCH_MODE_21 21
#define ELEMENTWISE_TPL_SCH_MODE_22 22
#define ELEMENTWISE_TPL_SCH_MODE_23 23
#define ELEMENTWISE_TPL_SCH_MODE_24 24
#define ELEMENTWISE_TPL_SCH_MODE_25 25
#define ELEMENTWISE_TPL_SCH_MODE_26 26
#define ELEMENTWISE_TPL_SCH_MODE_27 27
#define ELEMENTWISE_TPL_SCH_MODE_28 28
#define ELEMENTWISE_TPL_SCH_MODE_29 29
#define ELEMENTWISE_TPL_SCH_MODE_30 30
#define ELEMENTWISE_TPL_SCH_MODE_31 31

ASCENDC_TPL_ARGS_DECL(Transposev,
    ASCENDC_TPL_UINT_DECL(schMode, 5, 
    ASCENDC_TPL_UI_LIST, 
    ELEMENTWISE_TPL_SCH_MODE_0, 
    ELEMENTWISE_TPL_SCH_MODE_1,
    ELEMENTWISE_TPL_SCH_MODE_2,
    ELEMENTWISE_TPL_SCH_MODE_3,
    ELEMENTWISE_TPL_SCH_MODE_4,
    ELEMENTWISE_TPL_SCH_MODE_5,
    ELEMENTWISE_TPL_SCH_MODE_6,
    ELEMENTWISE_TPL_SCH_MODE_7,
    ELEMENTWISE_TPL_SCH_MODE_8,
    ELEMENTWISE_TPL_SCH_MODE_9,
    ELEMENTWISE_TPL_SCH_MODE_10,
    ELEMENTWISE_TPL_SCH_MODE_11,
    ELEMENTWISE_TPL_SCH_MODE_12,
    ELEMENTWISE_TPL_SCH_MODE_13,
    ELEMENTWISE_TPL_SCH_MODE_14,
    ELEMENTWISE_TPL_SCH_MODE_15,
    ELEMENTWISE_TPL_SCH_MODE_16,
    ELEMENTWISE_TPL_SCH_MODE_17,
    ELEMENTWISE_TPL_SCH_MODE_18,
    ELEMENTWISE_TPL_SCH_MODE_19,
    ELEMENTWISE_TPL_SCH_MODE_20,
    ELEMENTWISE_TPL_SCH_MODE_21,
    ELEMENTWISE_TPL_SCH_MODE_22,
    ELEMENTWISE_TPL_SCH_MODE_23,
    ELEMENTWISE_TPL_SCH_MODE_24,
    ELEMENTWISE_TPL_SCH_MODE_25,
    ELEMENTWISE_TPL_SCH_MODE_26,
    ELEMENTWISE_TPL_SCH_MODE_27,
    ELEMENTWISE_TPL_SCH_MODE_28,
    ELEMENTWISE_TPL_SCH_MODE_29,
    ELEMENTWISE_TPL_SCH_MODE_30,
    ELEMENTWISE_TPL_SCH_MODE_31),);

ASCENDC_TPL_SEL(ASCENDC_TPL_ARGS_SEL(
    ASCENDC_TPL_UINT_SEL(schMode, ASCENDC_TPL_UI_LIST, 
    ELEMENTWISE_TPL_SCH_MODE_0, 
    ELEMENTWISE_TPL_SCH_MODE_1,
    ELEMENTWISE_TPL_SCH_MODE_2,
    ELEMENTWISE_TPL_SCH_MODE_3,
    ELEMENTWISE_TPL_SCH_MODE_4,
    ELEMENTWISE_TPL_SCH_MODE_5,
    ELEMENTWISE_TPL_SCH_MODE_6,
    ELEMENTWISE_TPL_SCH_MODE_7,
    ELEMENTWISE_TPL_SCH_MODE_8,
    ELEMENTWISE_TPL_SCH_MODE_9,
    ELEMENTWISE_TPL_SCH_MODE_10,
    ELEMENTWISE_TPL_SCH_MODE_11,
    ELEMENTWISE_TPL_SCH_MODE_12,
    ELEMENTWISE_TPL_SCH_MODE_13,
    ELEMENTWISE_TPL_SCH_MODE_14,
    ELEMENTWISE_TPL_SCH_MODE_15,
    ELEMENTWISE_TPL_SCH_MODE_16,
    ELEMENTWISE_TPL_SCH_MODE_17,
    ELEMENTWISE_TPL_SCH_MODE_18,
    ELEMENTWISE_TPL_SCH_MODE_19,
    ELEMENTWISE_TPL_SCH_MODE_20,
    ELEMENTWISE_TPL_SCH_MODE_21,
    ELEMENTWISE_TPL_SCH_MODE_22,
    ELEMENTWISE_TPL_SCH_MODE_23,
    ELEMENTWISE_TPL_SCH_MODE_24,
    ELEMENTWISE_TPL_SCH_MODE_25,
    ELEMENTWISE_TPL_SCH_MODE_26,
    ELEMENTWISE_TPL_SCH_MODE_27,
    ELEMENTWISE_TPL_SCH_MODE_28,
    ELEMENTWISE_TPL_SCH_MODE_29,
    ELEMENTWISE_TPL_SCH_MODE_30,
    ELEMENTWISE_TPL_SCH_MODE_31)),);

#endif