/**
 * This program is free software, you can redistribute it and/or modify it.
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING
 * BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/*!
 * \file power_tiling_key.h
 * \brief power tiling key declare
*/
#ifndef __POWER_CUSTOM_TILING_KEY_H__
#define __POWER_CUSTOM_TILING_KEY_H__

#include "ascendc/host_api/tiling/template_argument.h"

// 定义49种调度模式常量
#define ELEMENTWISE_TPL_SCH_MODE_0 0
#define ELEMENTWISE_TPL_SCH_MODE_1 1
#define ELEMENTWISE_TPL_SCH_MODE_2 2
#define ELEMENTWISE_TPL_SCH_MODE_3 3
#define ELEMENTWISE_TPL_SCH_MODE_4 4
#define ELEMENTWISE_TPL_SCH_MODE_5 5
#define ELEMENTWISE_TPL_SCH_MODE_6 6
#define ELEMENTWISE_TPL_SCH_MODE_7 7
#define ELEMENTWISE_TPL_SCH_MODE_8 8
#define ELEMENTWISE_TPL_SCH_MODE_9 9
#define ELEMENTWISE_TPL_SCH_MODE_10 10
#define ELEMENTWISE_TPL_SCH_MODE_11 11
#define ELEMENTWISE_TPL_SCH_MODE_12 12
#define ELEMENTWISE_TPL_SCH_MODE_13 13
#define ELEMENTWISE_TPL_SCH_MODE_14 14
#define ELEMENTWISE_TPL_SCH_MODE_15 15
#define ELEMENTWISE_TPL_SCH_MODE_16 16
#define ELEMENTWISE_TPL_SCH_MODE_17 17
#define ELEMENTWISE_TPL_SCH_MODE_18 18
#define ELEMENTWISE_TPL_SCH_MODE_19 19
#define ELEMENTWISE_TPL_SCH_MODE_20 20
#define ELEMENTWISE_TPL_SCH_MODE_21 21
#define ELEMENTWISE_TPL_SCH_MODE_22 22
#define ELEMENTWISE_TPL_SCH_MODE_23 23
#define ELEMENTWISE_TPL_SCH_MODE_24 24
#define ELEMENTWISE_TPL_SCH_MODE_25 25
#define ELEMENTWISE_TPL_SCH_MODE_26 26
#define ELEMENTWISE_TPL_SCH_MODE_27 27
#define ELEMENTWISE_TPL_SCH_MODE_28 28
#define ELEMENTWISE_TPL_SCH_MODE_29 29
#define ELEMENTWISE_TPL_SCH_MODE_30 30
#define ELEMENTWISE_TPL_SCH_MODE_31 31
#define ELEMENTWISE_TPL_SCH_MODE_32 32
#define ELEMENTWISE_TPL_SCH_MODE_33 33
#define ELEMENTWISE_TPL_SCH_MODE_34 34
#define ELEMENTWISE_TPL_SCH_MODE_35 35
#define ELEMENTWISE_TPL_SCH_MODE_36 36
#define ELEMENTWISE_TPL_SCH_MODE_37 37
#define ELEMENTWISE_TPL_SCH_MODE_38 38
#define ELEMENTWISE_TPL_SCH_MODE_39 39
#define ELEMENTWISE_TPL_SCH_MODE_40 40
#define ELEMENTWISE_TPL_SCH_MODE_41 41
#define ELEMENTWISE_TPL_SCH_MODE_42 42
#define ELEMENTWISE_TPL_SCH_MODE_43 43
#define ELEMENTWISE_TPL_SCH_MODE_44 44
#define ELEMENTWISE_TPL_SCH_MODE_45 45
#define ELEMENTWISE_TPL_SCH_MODE_46 46
#define ELEMENTWISE_TPL_SCH_MODE_47 47
#define ELEMENTWISE_TPL_SCH_MODE_48 48

// 模板参数声明 - 使用6位表示49种模式 (2^6=64 > 49)
ASCENDC_TPL_ARGS_DECL(Power,
    ASCENDC_TPL_UINT_DECL(schMode, 6, 
    ASCENDC_TPL_UI_LIST, 
    ELEMENTWISE_TPL_SCH_MODE_0, 
    ELEMENTWISE_TPL_SCH_MODE_1,
    ELEMENTWISE_TPL_SCH_MODE_2,
    ELEMENTWISE_TPL_SCH_MODE_3,
    ELEMENTWISE_TPL_SCH_MODE_4,
    ELEMENTWISE_TPL_SCH_MODE_5,
    ELEMENTWISE_TPL_SCH_MODE_6,
    ELEMENTWISE_TPL_SCH_MODE_7,
    ELEMENTWISE_TPL_SCH_MODE_8,
    ELEMENTWISE_TPL_SCH_MODE_9,
    ELEMENTWISE_TPL_SCH_MODE_10,
    ELEMENTWISE_TPL_SCH_MODE_11,
    ELEMENTWISE_TPL_SCH_MODE_12,
    ELEMENTWISE_TPL_SCH_MODE_13,
    ELEMENTWISE_TPL_SCH_MODE_14,
    ELEMENTWISE_TPL_SCH_MODE_15,
    ELEMENTWISE_TPL_SCH_MODE_16,
    ELEMENTWISE_TPL_SCH_MODE_17,
    ELEMENTWISE_TPL_SCH_MODE_18,
    ELEMENTWISE_TPL_SCH_MODE_19,
    ELEMENTWISE_TPL_SCH_MODE_20,
    ELEMENTWISE_TPL_SCH_MODE_21,
    ELEMENTWISE_TPL_SCH_MODE_22,
    ELEMENTWISE_TPL_SCH_MODE_23,
    ELEMENTWISE_TPL_SCH_MODE_24,
    ELEMENTWISE_TPL_SCH_MODE_25,
    ELEMENTWISE_TPL_SCH_MODE_26,
    ELEMENTWISE_TPL_SCH_MODE_27,
    ELEMENTWISE_TPL_SCH_MODE_28,
    ELEMENTWISE_TPL_SCH_MODE_29,
    ELEMENTWISE_TPL_SCH_MODE_30,
    ELEMENTWISE_TPL_SCH_MODE_31,
    ELEMENTWISE_TPL_SCH_MODE_32,
    ELEMENTWISE_TPL_SCH_MODE_33,
    ELEMENTWISE_TPL_SCH_MODE_34,
    ELEMENTWISE_TPL_SCH_MODE_35,
    ELEMENTWISE_TPL_SCH_MODE_36,
    ELEMENTWISE_TPL_SCH_MODE_37,
    ELEMENTWISE_TPL_SCH_MODE_38,
    ELEMENTWISE_TPL_SCH_MODE_39,
    ELEMENTWISE_TPL_SCH_MODE_40,
    ELEMENTWISE_TPL_SCH_MODE_41,
    ELEMENTWISE_TPL_SCH_MODE_42,
    ELEMENTWISE_TPL_SCH_MODE_43,
    ELEMENTWISE_TPL_SCH_MODE_44,
    ELEMENTWISE_TPL_SCH_MODE_45,
    ELEMENTWISE_TPL_SCH_MODE_46,
    ELEMENTWISE_TPL_SCH_MODE_47,
    ELEMENTWISE_TPL_SCH_MODE_48),);

// 模板选择器
ASCENDC_TPL_SEL(ASCENDC_TPL_ARGS_SEL(
    ASCENDC_TPL_UINT_SEL(schMode, ASCENDC_TPL_UI_LIST, 
    ELEMENTWISE_TPL_SCH_MODE_0, 
    ELEMENTWISE_TPL_SCH_MODE_1,
    ELEMENTWISE_TPL_SCH_MODE_2,
    ELEMENTWISE_TPL_SCH_MODE_3,
    ELEMENTWISE_TPL_SCH_MODE_4,
    ELEMENTWISE_TPL_SCH_MODE_5,
    ELEMENTWISE_TPL_SCH_MODE_6,
    ELEMENTWISE_TPL_SCH_MODE_7,
    ELEMENTWISE_TPL_SCH_MODE_8,
    ELEMENTWISE_TPL_SCH_MODE_9,
    ELEMENTWISE_TPL_SCH_MODE_10,
    ELEMENTWISE_TPL_SCH_MODE_11,
    ELEMENTWISE_TPL_SCH_MODE_12,
    ELEMENTWISE_TPL_SCH_MODE_13,
    ELEMENTWISE_TPL_SCH_MODE_14,
    ELEMENTWISE_TPL_SCH_MODE_15,
    ELEMENTWISE_TPL_SCH_MODE_16,
    ELEMENTWISE_TPL_SCH_MODE_17,
    ELEMENTWISE_TPL_SCH_MODE_18,
    ELEMENTWISE_TPL_SCH_MODE_19,
    ELEMENTWISE_TPL_SCH_MODE_20,
    ELEMENTWISE_TPL_SCH_MODE_21,
    ELEMENTWISE_TPL_SCH_MODE_22,
    ELEMENTWISE_TPL_SCH_MODE_23,
    ELEMENTWISE_TPL_SCH_MODE_24,
    ELEMENTWISE_TPL_SCH_MODE_25,
    ELEMENTWISE_TPL_SCH_MODE_26,
    ELEMENTWISE_TPL_SCH_MODE_27,
    ELEMENTWISE_TPL_SCH_MODE_28,
    ELEMENTWISE_TPL_SCH_MODE_29,
    ELEMENTWISE_TPL_SCH_MODE_30,
    ELEMENTWISE_TPL_SCH_MODE_31,
    ELEMENTWISE_TPL_SCH_MODE_32,
    ELEMENTWISE_TPL_SCH_MODE_33,
    ELEMENTWISE_TPL_SCH_MODE_34,
    ELEMENTWISE_TPL_SCH_MODE_35,
    ELEMENTWISE_TPL_SCH_MODE_36,
    ELEMENTWISE_TPL_SCH_MODE_37,
    ELEMENTWISE_TPL_SCH_MODE_38,
    ELEMENTWISE_TPL_SCH_MODE_39,
    ELEMENTWISE_TPL_SCH_MODE_40,
    ELEMENTWISE_TPL_SCH_MODE_41,
    ELEMENTWISE_TPL_SCH_MODE_42,
    ELEMENTWISE_TPL_SCH_MODE_43,
    ELEMENTWISE_TPL_SCH_MODE_44,
    ELEMENTWISE_TPL_SCH_MODE_45,
    ELEMENTWISE_TPL_SCH_MODE_46,
    ELEMENTWISE_TPL_SCH_MODE_47,
    ELEMENTWISE_TPL_SCH_MODE_48)),);

#endif // __POWER_CUSTOM_TILING_KEY_H__